/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	"/v1/audit/logs": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * QueryWriteLog searches the audit log for config change events.
		 *     All filter parameters are optional — omit a filter to match all values.
		 */
		get: operations["AuditService_QueryWriteLog"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/v1/schemas": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** ListSchemas returns all schemas, ordered by creation time (newest first). */
		get: operations["SchemaService_ListSchemas"];
		put?: never;
		/** CreateSchema creates a new schema with an initial draft version (v1). */
		post: operations["SchemaService_CreateSchema"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/v1/schemas/import": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * ImportSchema creates a schema (or new version) from YAML.
		 *     Full-replace semantics: the YAML defines the complete field set.
		 *     Returns AlreadyExists if the imported fields are identical to the latest version.
		 */
		post: operations["SchemaService_ImportSchema"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/v1/schemas/{id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** GetSchema retrieves a schema by ID, optionally at a specific version. */
		get: operations["SchemaService_GetSchema"];
		put?: never;
		post?: never;
		/** DeleteSchema permanently deletes a schema and all its versions. Cascades to tenants. */
		delete: operations["SchemaService_DeleteSchema"];
		options?: never;
		head?: never;
		/** UpdateSchema creates a new draft version by merging field changes with the latest version. */
		patch: operations["SchemaService_UpdateSchema"];
		trace?: never;
	};
	"/v1/schemas/{id}/export": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** ExportSchema serializes a schema version to YAML. */
		get: operations["SchemaService_ExportSchema"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/v1/schemas/{id}/publish": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * PublishSchema marks a schema version as published and immutable.
		 *     Only published versions can be assigned to tenants.
		 */
		post: operations["SchemaService_PublishSchema"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/v1/tenants": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** ListTenants returns tenants, optionally filtered by schema. */
		get: operations["SchemaService_ListTenants"];
		put?: never;
		/** CreateTenant creates a new tenant assigned to a published schema version. */
		post: operations["SchemaService_CreateTenant"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/v1/tenants/{id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** GetTenant retrieves a tenant by ID. */
		get: operations["SchemaService_GetTenant"];
		put?: never;
		post?: never;
		/** DeleteTenant permanently deletes a tenant and all its configuration data. */
		delete: operations["SchemaService_DeleteTenant"];
		options?: never;
		head?: never;
		/** UpdateTenant updates a tenant's name or upgrades its schema version. */
		patch: operations["SchemaService_UpdateTenant"];
		trace?: never;
	};
	"/v1/tenants/{tenantId}/config": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** GetConfig returns the full resolved configuration for a tenant. */
		get: operations["ConfigService_GetConfig"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/v1/tenants/{tenantId}/config/export": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** ExportConfig serializes a tenant's configuration to YAML. */
		get: operations["ConfigService_ExportConfig"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/v1/tenants/{tenantId}/config/fields/{fieldPath}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** GetField returns a single configuration value by field path. */
		get: operations["ConfigService_GetField"];
		/** SetField sets a single configuration value, creating a new config version. */
		put: operations["ConfigService_SetField"];
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/v1/tenants/{tenantId}/config/import": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** ImportConfig applies configuration values from YAML. */
		post: operations["ConfigService_ImportConfig"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/v1/tenants/{tenantId}/config:batchGet": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * GetFields returns multiple configuration values by field paths.
		 *     Fields that don't exist are silently omitted from the response.
		 */
		post: operations["ConfigService_GetFields"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/v1/tenants/{tenantId}/config:batchSet": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** SetFields sets multiple configuration values in a single config version. */
		post: operations["ConfigService_SetFields"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/v1/tenants/{tenantId}/config:subscribe": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Subscribe opens a server-streaming connection that pushes ConfigChange events
		 *     whenever the tenant's configuration is modified. The stream remains open until
		 *     the client disconnects or the server shuts down.
		 */
		get: operations["ConfigService_Subscribe"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/v1/tenants/{tenantId}/locks": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** ListFieldLocks returns all active field locks for a tenant. */
		get: operations["SchemaService_ListFieldLocks"];
		put?: never;
		/** LockField prevents a field from being modified. */
		post: operations["SchemaService_LockField"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/v1/tenants/{tenantId}/locks/{fieldPath}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		/** UnlockField removes a field lock, allowing modifications again. */
		delete: operations["SchemaService_UnlockField"];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/v1/tenants/{tenantId}/unused-fields": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * GetUnusedFields returns field paths that have not been read since the given time.
		 *     Useful for identifying configuration fields that may be safe to deprecate.
		 */
		get: operations["AuditService_GetUnusedFields"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/v1/tenants/{tenantId}/usage": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** GetTenantUsage returns aggregated read statistics for all fields of a tenant. */
		get: operations["AuditService_GetTenantUsage"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/v1/tenants/{tenantId}/usage/{fieldPath}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** GetFieldUsage returns aggregated read statistics for a specific field. */
		get: operations["AuditService_GetFieldUsage"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/v1/tenants/{tenantId}/versions": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** ListVersions returns config version history for a tenant (newest first). */
		get: operations["ConfigService_ListVersions"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/v1/tenants/{tenantId}/versions/{version}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** GetVersion retrieves metadata for a specific config version. */
		get: operations["ConfigService_GetVersion"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/v1/tenants/{tenantId}/versions/{version}:rollback": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * RollbackToVersion creates a new version with the same values as the target version.
		 *     This does not delete intermediate versions — it creates a new version that
		 *     copies the target's values.
		 */
		post: operations["ConfigService_RollbackToVersion"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/v1/version": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** GetServerVersion returns the server's build version and commit hash. */
		get: operations["VersionService_GetServerVersion"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		ConfigServiceGetFieldsBody: {
			/** @description Dot-separated field paths to retrieve. */
			fieldPaths?: string[];
			/**
			 * Format: int32
			 * @description Config version to read from. If omitted, reads from the latest version.
			 */
			version?: number;
			/**
			 * @description When true, includes value-level descriptions.
			 *     This bypasses the Redis cache and reads directly from the database.
			 */
			includeDescriptions?: boolean;
		};
		ConfigServiceImportConfigBody: {
			/**
			 * Format: byte
			 * @description YAML-encoded configuration values to import.
			 */
			yamlContent?: string;
			/** @description Description for the new config version created by the import. */
			description?: string;
			mode?: components["schemas"]["v1ImportMode"];
		};
		ConfigServiceSetFieldBody: {
			value?: components["schemas"]["v1TypedValue"];
			/**
			 * @description Optimistic concurrency control: the checksum from a previous GetField/GetConfig
			 *     response. If provided and the field's current checksum doesn't match, the
			 *     request fails with ABORTED. This prevents lost updates when multiple actors
			 *     modify the same field concurrently.
			 */
			expectedChecksum?: string;
			/** @description Version-level description explaining why this change was made. */
			description?: string;
			/**
			 * @description Value-level description explaining what this specific value means.
			 *     Retrievable via include_description in read requests.
			 */
			valueDescription?: string;
		};
		ConfigServiceSetFieldsBody: {
			/**
			 * @description Field updates to apply. All updates are applied atomically in a single
			 *     config version. If any update fails validation (checksum, field lock),
			 *     no changes are committed.
			 */
			updates?: components["schemas"]["v1FieldUpdate"][];
			/** @description Version-level description explaining why these changes were made. */
			description?: string;
		};
		SchemaServiceLockFieldBody: {
			/** @description Dot-separated field path to lock (e.g. "payments.currency"). */
			fieldPath?: string;
			/**
			 * @description For enum fields: lock only these specific values. If empty, the
			 *     entire field is locked regardless of value.
			 */
			lockedValues?: string[];
		};
		SchemaServicePublishSchemaBody: {
			/**
			 * Format: int32
			 * @description The version number to publish. Must be an existing draft version.
			 *     Once published, the version is immutable.
			 */
			version?: number;
		};
		SchemaServiceUpdateSchemaBody: {
			/** @description Description of what changed in this version. */
			versionDescription?: string;
			/**
			 * @description Fields to add or modify. Existing fields not listed here are carried
			 *     forward unchanged from the latest version.
			 */
			fields?: components["schemas"]["v1SchemaField"][];
			/** @description Dot-separated paths of fields to remove from the new version. */
			removeFields?: string[];
		};
		SchemaServiceUpdateTenantBody: {
			/** @description New name for the tenant. Must be a valid slug if provided. */
			name?: string;
			/**
			 * Format: int32
			 * @description Upgrade to a new schema version. The new version must belong to the
			 *     same schema and must be published.
			 */
			schemaVersion?: number;
		};
		protobufAny: {
			"@type"?: string;
		} & {
			[key: string]: unknown;
		};
		rpcStatus: {
			/** Format: int32 */
			code?: number;
			message?: string;
			details?: components["schemas"]["protobufAny"][];
		};
		/**
		 * @description AuditEntry represents a write event recorded in the audit log.
		 *     Every config mutation (SetField, SetFields, RollbackToVersion) creates
		 *     one or more audit entries atomically with the config change.
		 */
		v1AuditEntry: {
			/** @description Server-assigned unique identifier (UUID). */
			id?: string;
			/** @description The tenant affected (UUID). */
			tenantId?: string;
			/** @description The actor who performed the action (from JWT subject). */
			actor?: string;
			/** @description The action type (e.g. "set_field", "rollback"). */
			action?: string;
			/** @description The field that was changed. Present for set_field actions. */
			fieldPath?: string;
			/** @description The previous value. Present for set_field actions. */
			oldValue?: string;
			/**
			 * @description The new value. Present for set_field actions.
			 *     For rollback actions, contains the target version (e.g. "v2").
			 */
			newValue?: string;
			/**
			 * Format: int32
			 * @description The config version number created by this action.
			 */
			configVersion?: number;
			/**
			 * Format: date-time
			 * @description When the audit entry was created.
			 */
			createdAt?: string;
		};
		/** @description Config represents the full resolved configuration for a tenant at a specific version. */
		v1Config: {
			/** @description The tenant this config belongs to (UUID). */
			tenantId?: string;
			/**
			 * Format: int32
			 * @description The version number this config was resolved at.
			 */
			version?: number;
			/** @description All configuration values at this version. */
			values?: components["schemas"]["v1ConfigValue"][];
		};
		/**
		 * @description ConfigChange represents a real-time change event pushed to subscribers
		 *     via the Subscribe streaming RPC.
		 */
		v1ConfigChange: {
			/** @description The tenant whose config changed (UUID). */
			tenantId?: string;
			/**
			 * Format: int32
			 * @description The new config version number created by this change.
			 */
			version?: number;
			/** @description The field that was changed. */
			fieldPath?: string;
			oldValue?: components["schemas"]["v1TypedValue"];
			newValue?: components["schemas"]["v1TypedValue"];
			/** @description The actor who made the change. */
			changedBy?: string;
			/**
			 * Format: date-time
			 * @description When the change occurred.
			 */
			changedAt?: string;
		};
		/** @description ConfigValue represents a single configuration value at a point in time. */
		v1ConfigValue: {
			/** @description Dot-separated field path (e.g. "payments.fee"). */
			fieldPath?: string;
			value?: components["schemas"]["v1TypedValue"];
			/**
			 * @description Checksum of the value (xxHash). Used for optimistic concurrency control
			 *     in SetField/SetFields via expected_checksum.
			 */
			checksum?: string;
			/**
			 * @description Human-readable description explaining this specific value.
			 *     Only populated when include_description(s) is true in the request.
			 */
			description?: string;
		};
		/**
		 * @description ConfigVersion represents a point-in-time snapshot of configuration changes.
		 *     Each write operation (SetField, SetFields, RollbackToVersion) creates a new
		 *     config version. Versions store only the changed fields (delta storage) — the
		 *     full config at any version is the union of all deltas up to that version.
		 */
		v1ConfigVersion: {
			/** @description Server-assigned unique identifier (UUID). */
			id?: string;
			/** @description The tenant this version belongs to (UUID). */
			tenantId?: string;
			/**
			 * Format: int32
			 * @description Version number (monotonically increasing, starting at 1).
			 */
			version?: number;
			/** @description Description of what changed in this version. */
			description?: string;
			/** @description The actor who created this version (from JWT subject, or "unknown" if auth is disabled). */
			createdBy?: string;
			/**
			 * Format: date-time
			 * @description When this version was created.
			 */
			createdAt?: string;
		};
		v1CreateSchemaRequest: {
			/**
			 * @description Unique name for the schema. Must be a valid slug: lowercase alphanumeric
			 *     and hyphens, 1-63 characters (e.g. "payment-config", "settlement-rules").
			 */
			name?: string;
			/** @description Human-readable description of the schema's purpose. */
			description?: string;
			/** @description Initial field definitions for version 1. At least one field is required. */
			fields?: components["schemas"]["v1SchemaField"][];
		};
		v1CreateSchemaResponse: {
			schema?: components["schemas"]["v1Schema"];
		};
		v1CreateTenantRequest: {
			/**
			 * @description Unique name for the tenant. Must be a valid slug: lowercase alphanumeric
			 *     and hyphens, 1-63 characters (e.g. "acme-corp", "tenant-42").
			 */
			name?: string;
			/** @description The schema to assign to this tenant (UUID). */
			schemaId?: string;
			/**
			 * Format: int32
			 * @description The schema version to use. Must be a published version.
			 */
			schemaVersion?: number;
		};
		v1CreateTenantResponse: {
			tenant?: components["schemas"]["v1Tenant"];
		};
		v1DeleteSchemaResponse: Record<string, never>;
		v1DeleteTenantResponse: Record<string, never>;
		v1ExportConfigResponse: {
			/**
			 * Format: byte
			 * @description YAML-encoded configuration values.
			 */
			yamlContent?: string;
		};
		v1ExportSchemaResponse: {
			/**
			 * Format: byte
			 * @description YAML-encoded schema (syntax v1). Includes schema name, description,
			 *     version, and all field definitions with OAS-style constraint naming.
			 *     Server-generated fields (id, checksum, published, created_at) are excluded.
			 */
			yamlContent?: string;
		};
		/**
		 * ExternalDocs links to external documentation.
		 *     OAS: External Documentation Object
		 */
		v1ExternalDocs: {
			/** @description Human-readable description of the external documentation. */
			description?: string;
			/** @description URL to the external documentation. */
			url?: string;
		};
		/**
		 * @description FieldConstraints defines validation rules for a schema field.
		 *     Which constraints apply depends on the field's type — see FieldType docs.
		 */
		v1FieldConstraints: {
			/**
			 * Format: double
			 * @description For integer/number/duration: minimum allowed value (inclusive, >=).
			 */
			min?: number;
			/**
			 * Format: double
			 * @description For integer/number/duration: maximum allowed value (inclusive, <=).
			 */
			max?: number;
			/**
			 * @description Regular expression pattern the value must match.
			 *     Applies to string-typed fields. Uses RE2 syntax.
			 */
			regex?: string;
			/**
			 * @description Allowed values. If non-empty, the value must be one of these.
			 *     Applies to any field type.
			 */
			enumValues?: string[];
			/**
			 * @description JSON Schema document for structural validation of json-typed fields.
			 *     Encoded as a JSON string.
			 */
			jsonSchema?: string;
			/**
			 * Format: double
			 * @description For integer/number/duration: exclusive minimum (strict, >).
			 */
			exclusiveMin?: number;
			/**
			 * Format: double
			 * @description For integer/number/duration: exclusive maximum (strict, <).
			 */
			exclusiveMax?: number;
			/**
			 * Format: int32
			 * @description For string: minimum allowed length.
			 */
			minLength?: number;
			/**
			 * Format: int32
			 * @description For string: maximum allowed length.
			 */
			maxLength?: number;
		};
		/** @description FieldExample represents a named example value for a schema field. */
		v1FieldExample: {
			/** @description The example value, encoded as a string matching the field type. */
			value?: string;
			/** @description Short description of what this example demonstrates. */
			summary?: string;
		};
		/**
		 * @description FieldLock prevents a configuration field from being modified by non-superadmin users.
		 *     Superadmins bypass all field locks.
		 */
		v1FieldLock: {
			/** @description The tenant this lock applies to (UUID). */
			tenantId?: string;
			/** @description The dot-separated field path that is locked. */
			fieldPath?: string;
			/**
			 * @description For enum fields: the specific subset of values that are locked
			 *     (not editable by admin). If empty, the entire field is locked.
			 */
			lockedValues?: string[];
		};
		/**
		 * @description FieldType enumerates the supported configuration value types.
		 *     Each type maps to a specific field in the TypedValue oneof.
		 *
		 *      - FIELD_TYPE_INT: Integer value. Encoded as a decimal string (e.g. "42", "-1").
		 *     Supports minimum/maximum constraints on the numeric value.
		 *      - FIELD_TYPE_STRING: Free-form string value.
		 *     Supports minimum/maximum constraints on string length, pattern (regex),
		 *     and enum constraints.
		 *      - FIELD_TYPE_TIME: Timestamp value. Encoded as an RFC 3339 string (e.g. "2025-01-15T09:30:00Z").
		 *      - FIELD_TYPE_DURATION: Duration value. Encoded as a Go-style duration string (e.g. "24h", "30m", "500ms").
		 *     Supports minimum/maximum constraints on the duration in seconds.
		 *      - FIELD_TYPE_URL: URL value. Must be a valid absolute URL.
		 *      - FIELD_TYPE_JSON: JSON value. Stored as a JSON-encoded string.
		 *     Supports json_schema constraint for structural validation.
		 *      - FIELD_TYPE_NUMBER: Floating-point number value. Encoded as a decimal string (e.g. "3.14", "0.025").
		 *     Supports minimum/maximum constraints on the numeric value.
		 *      - FIELD_TYPE_BOOL: Boolean value. Encoded as "true" or "false".
		 * @default FIELD_TYPE_UNSPECIFIED
		 * @enum {string}
		 */
		v1FieldType:
			| "FIELD_TYPE_UNSPECIFIED"
			| "FIELD_TYPE_INT"
			| "FIELD_TYPE_STRING"
			| "FIELD_TYPE_TIME"
			| "FIELD_TYPE_DURATION"
			| "FIELD_TYPE_URL"
			| "FIELD_TYPE_JSON"
			| "FIELD_TYPE_NUMBER"
			| "FIELD_TYPE_BOOL";
		/** @description FieldUpdate represents a single field change within a SetFields batch. */
		v1FieldUpdate: {
			/** @description Dot-separated field path. */
			fieldPath?: string;
			value?: components["schemas"]["v1TypedValue"];
			/**
			 * @description Optimistic concurrency control checksum for this specific field.
			 *     See SetFieldRequest.expected_checksum for details.
			 */
			expectedChecksum?: string;
			/** @description Value-level description for this specific field. */
			valueDescription?: string;
		};
		v1GetConfigResponse: {
			config?: components["schemas"]["v1Config"];
		};
		v1GetFieldResponse: {
			value?: components["schemas"]["v1ConfigValue"];
		};
		v1GetFieldUsageResponse: {
			stats?: components["schemas"]["v1UsageStats"];
		};
		v1GetFieldsResponse: {
			/** @description The requested values. Fields that don't exist are omitted (not an error). */
			values?: components["schemas"]["v1ConfigValue"][];
		};
		v1GetSchemaResponse: {
			schema?: components["schemas"]["v1Schema"];
		};
		v1GetServerVersionResponse: {
			/** @description Semantic version string (e.g. "1.2.3" or "dev"). */
			version?: string;
			/** @description Git commit hash. */
			commit?: string;
		};
		v1GetTenantResponse: {
			tenant?: components["schemas"]["v1Tenant"];
		};
		v1GetTenantUsageResponse: {
			/** @description Per-field usage statistics, ordered by field path. */
			fieldStats?: components["schemas"]["v1UsageStats"][];
		};
		v1GetUnusedFieldsResponse: {
			/** @description Dot-separated paths of fields with no reads since the specified time. */
			fieldPaths?: string[];
		};
		v1GetVersionResponse: {
			configVersion?: components["schemas"]["v1ConfigVersion"];
		};
		v1ImportConfigResponse: {
			configVersion?: components["schemas"]["v1ConfigVersion"];
		};
		/**
		 * @description ImportMode controls how imported values interact with existing config.
		 *
		 *      - IMPORT_MODE_UNSPECIFIED: Unspecified defaults to merge behavior.
		 *      - IMPORT_MODE_MERGE: Merge: update fields from YAML that differ, keep runtime overrides
		 *     for fields not in the YAML.
		 *      - IMPORT_MODE_REPLACE: Replace: full replace — all fields from YAML are set, fields not in YAML
		 *     are not carried forward. Runtime overrides are wiped.
		 *      - IMPORT_MODE_DEFAULTS: Defaults: only set fields that have no value yet. Fields that already have
		 *     a value are skipped regardless of the YAML content.
		 * @default IMPORT_MODE_UNSPECIFIED
		 * @enum {string}
		 */
		v1ImportMode:
			| "IMPORT_MODE_UNSPECIFIED"
			| "IMPORT_MODE_MERGE"
			| "IMPORT_MODE_REPLACE"
			| "IMPORT_MODE_DEFAULTS";
		v1ImportSchemaRequest: {
			/**
			 * Format: byte
			 * @description YAML-encoded schema (syntax v1). Must include `syntax`, `name`, and `fields`.
			 *
			 *     Import uses full-replace semantics:
			 *     - If no schema with this name exists: creates a new schema with version 1.
			 *     - If a schema exists and fields differ from latest: creates the next version.
			 *     - If a schema exists and fields are identical: returns AlreadyExists error.
			 *
			 *     Imported versions are created as drafts (unpublished) unless auto_publish is true.
			 *     The `version` field in the YAML is informational — the server assigns
			 *     the next version number automatically.
			 */
			yamlContent?: string;
			/**
			 * @description When true, the imported version is automatically published after creation.
			 *     If the schema already exists and fields are identical (AlreadyExists), this has no effect.
			 */
			autoPublish?: boolean;
		};
		v1ImportSchemaResponse: {
			schema?: components["schemas"]["v1Schema"];
		};
		v1ListFieldLocksResponse: {
			/** @description All active field locks for the tenant. */
			locks?: components["schemas"]["v1FieldLock"][];
		};
		v1ListSchemasResponse: {
			/** @description Schemas with their latest version. */
			schemas?: components["schemas"]["v1Schema"][];
			/** @description Token for the next page. Empty if no more results. */
			nextPageToken?: string;
		};
		v1ListTenantsResponse: {
			tenants?: components["schemas"]["v1Tenant"][];
			/** @description Token for the next page. Empty if no more results. */
			nextPageToken?: string;
		};
		v1ListVersionsResponse: {
			/** @description Config versions, ordered by version number descending (newest first). */
			versions?: components["schemas"]["v1ConfigVersion"][];
			/** @description Token for the next page. Empty if no more results. */
			nextPageToken?: string;
		};
		v1LockFieldResponse: Record<string, never>;
		v1PublishSchemaResponse: {
			schema?: components["schemas"]["v1Schema"];
		};
		v1QueryWriteLogResponse: {
			/** @description Audit entries matching the filters, ordered by created_at descending. */
			entries?: components["schemas"]["v1AuditEntry"][];
			/** @description Token for the next page. Empty if no more results. */
			nextPageToken?: string;
		};
		v1RollbackToVersionResponse: {
			configVersion?: components["schemas"]["v1ConfigVersion"];
		};
		/**
		 * @description Schema represents a configuration schema template.
		 *     Schemas define the allowed fields and their types for tenant configurations.
		 *     Each schema is versioned — updates create new immutable versions.
		 */
		v1Schema: {
			/** @description Server-assigned unique identifier (UUID). */
			id?: string;
			/**
			 * @description Unique name for this schema. Must be a valid slug: lowercase alphanumeric
			 *     characters and hyphens, 1-63 characters, matching [a-z0-9]([a-z0-9-]*[a-z0-9])?.
			 */
			name?: string;
			/** @description Human-readable description of the schema's purpose. */
			description?: string;
			/**
			 * Format: int32
			 * @description Schema version number (monotonically increasing, starting at 1).
			 */
			version?: number;
			/**
			 * Format: int32
			 * @description The version this was derived from. Absent for the initial version (v1).
			 */
			parentVersion?: number;
			/** @description Description of what changed in this version. */
			versionDescription?: string;
			/**
			 * @description Deterministic checksum of the field definitions (type, constraints, path).
			 *     Used for change detection on import.
			 */
			checksum?: string;
			/**
			 * @description Whether this version is published. Only published versions can be
			 *     assigned to tenants. Published versions are immutable.
			 */
			published?: boolean;
			/** @description The fields defined in this schema version. */
			fields?: components["schemas"]["v1SchemaField"][];
			/**
			 * Format: date-time
			 * @description When this version was created.
			 */
			createdAt?: string;
			info?: components["schemas"]["v1SchemaInfo"];
		};
		/**
		 * SchemaContact contains contact information for a schema owner.
		 *     OAS: Contact Object
		 */
		v1SchemaContact: {
			/** @description Contact name (person or team). */
			name?: string;
			/** @description Contact email address. */
			email?: string;
			/** @description Contact URL (e.g. team wiki page). */
			url?: string;
		};
		/** @description SchemaField defines a single field within a configuration schema. */
		v1SchemaField: {
			/**
			 * @description Dot-separated hierarchical path (e.g. "payments.settlement.window").
			 *     Must be unique within a schema version.
			 */
			path?: string;
			type?: components["schemas"]["v1FieldType"];
			constraints?: components["schemas"]["v1FieldConstraints"];
			/** @description Whether this field accepts empty/null values. */
			nullable?: boolean;
			/**
			 * @description Whether this field is deprecated. Deprecated fields are still readable
			 *     but clients should migrate to redirect_to if set.
			 */
			deprecated?: boolean;
			/** @description When deprecated, reads of this field can be redirected to this path. */
			redirectTo?: string;
			/** @description Default value for this field, encoded as a string matching the field type. */
			defaultValue?: string;
			/** @description Human-readable description of the field's purpose. */
			description?: string;
			/**
			 * Human-friendly display name (e.g. "Fee Rate" for path "payments.fee_rate").
			 *     OAS: title
			 */
			title?: string;
			/**
			 * Single example value, encoded as a string matching the field type.
			 *     OAS: example
			 */
			example?: string;
			/**
			 * Named examples with optional summary. Key is example name.
			 *     OAS: examples
			 */
			examples?: {
				[key: string]: components["schemas"]["v1FieldExample"];
			};
			externalDocs?: components["schemas"]["v1ExternalDocs"];
			/**
			 * Tags for grouping and categorization beyond the dot-prefix hierarchy.
			 *     OAS: x-tags
			 */
			tags?: string[];
			/**
			 * Semantic format hint within the base type (e.g. "email", "semver", "percentage").
			 *     Informational — not enforced by validation.
			 *     OAS: format
			 */
			format?: string;
			/**
			 * Whether this field is system-managed and not user-editable.
			 *     OAS: readOnly
			 */
			readOnly?: boolean;
			/** @description Whether this field can only be set once and becomes immutable after. */
			writeOnce?: boolean;
			/** @description Whether this field's value should be masked in logs and UI. */
			sensitive?: boolean;
		};
		/**
		 * SchemaInfo contains optional metadata about a schema's ownership and context.
		 *     OAS: Info Object
		 */
		v1SchemaInfo: {
			/**
			 * Human-friendly display title for the schema.
			 *     OAS: info.title
			 */
			title?: string;
			/** @description Schema owner identifier (person, team, or service). */
			author?: string;
			contact?: components["schemas"]["v1SchemaContact"];
			/** @description Key-value labels for filtering and categorization. */
			labels?: {
				[key: string]: string;
			};
		};
		v1SetFieldResponse: {
			configVersion?: components["schemas"]["v1ConfigVersion"];
		};
		v1SetFieldsResponse: {
			configVersion?: components["schemas"]["v1ConfigVersion"];
		};
		v1SubscribeResponse: {
			change?: components["schemas"]["v1ConfigChange"];
		};
		/**
		 * @description Tenant represents an organization or entity that has its own configuration
		 *     based on an assigned schema version.
		 */
		v1Tenant: {
			/** @description Server-assigned unique identifier (UUID). */
			id?: string;
			/**
			 * @description Unique name for this tenant. Must be a valid slug: lowercase alphanumeric
			 *     characters and hyphens, 1-63 characters, matching [a-z0-9]([a-z0-9-]*[a-z0-9])?.
			 */
			name?: string;
			/** @description The schema this tenant's configuration is based on (UUID). */
			schemaId?: string;
			/**
			 * Format: int32
			 * @description The specific schema version assigned to this tenant.
			 *     Must reference a published schema version.
			 */
			schemaVersion?: number;
			/**
			 * Format: date-time
			 * @description When the tenant was created.
			 */
			createdAt?: string;
			/**
			 * Format: date-time
			 * @description When the tenant was last updated (name or schema version change).
			 */
			updatedAt?: string;
		};
		/**
		 * @description TypedValue holds a configuration value with its native type.
		 *     An unset oneof (no field present) represents a null value.
		 */
		v1TypedValue: {
			/**
			 * Format: int64
			 * @description Integer value.
			 */
			integerValue?: string;
			/**
			 * Format: double
			 * @description Floating-point number value.
			 */
			numberValue?: number;
			/** @description Free-form string value. */
			stringValue?: string;
			/** @description Boolean value. */
			boolValue?: boolean;
			/**
			 * Format: date-time
			 * @description Timestamp value.
			 */
			timeValue?: string;
			/** @description Duration value. */
			durationValue?: string;
			/** @description URL value (must be a valid absolute URL). */
			urlValue?: string;
			/** @description JSON value (must be valid JSON). */
			jsonValue?: string;
		};
		v1UnlockFieldResponse: Record<string, never>;
		v1UpdateSchemaResponse: {
			schema?: components["schemas"]["v1Schema"];
		};
		v1UpdateTenantResponse: {
			tenant?: components["schemas"]["v1Tenant"];
		};
		/** @description UsageStats represents aggregated read usage statistics for a config field. */
		v1UsageStats: {
			/** @description The tenant (UUID). */
			tenantId?: string;
			/** @description The field path. */
			fieldPath?: string;
			/**
			 * Format: int64
			 * @description Total number of reads across the queried time range.
			 */
			readCount?: string;
			/** @description The last actor who read this field (if tracked). */
			lastReadBy?: string;
			/**
			 * Format: date-time
			 * @description When this field was last read (if tracked).
			 */
			lastReadAt?: string;
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
	AuditService_QueryWriteLog: {
		parameters: {
			query?: {
				/** @description Filter by tenant ID (UUID). If omitted, returns entries across all tenants. */
				tenantId?: string;
				/** @description Filter by actor (JWT subject). If omitted, matches all actors. */
				actor?: string;
				/** @description Filter by field path. If omitted, matches all fields. */
				fieldPath?: string;
				/** @description Filter entries created at or after this time. If omitted, no lower bound. */
				startTime?: string;
				/** @description Filter entries created at or before this time. If omitted, no upper bound. */
				endTime?: string;
				/** @description Maximum number of results to return. Defaults to 50, max 100. */
				pageSize?: number;
				/** @description Pagination token from a previous QueryWriteLogResponse. */
				pageToken?: string;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description A successful response. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["v1QueryWriteLogResponse"];
				};
			};
			/** @description An unexpected error response. */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["rpcStatus"];
				};
			};
		};
	};
	SchemaService_ListSchemas: {
		parameters: {
			query?: {
				/** @description Filter schemas by name prefix. Currently reserved for future use. */
				nameFilter?: string;
				/** @description Maximum number of results to return. Defaults to 50, max 100. */
				pageSize?: number;
				/** @description Pagination token from a previous ListSchemasResponse. */
				pageToken?: string;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description A successful response. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["v1ListSchemasResponse"];
				};
			};
			/** @description An unexpected error response. */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["rpcStatus"];
				};
			};
		};
	};
	SchemaService_CreateSchema: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["v1CreateSchemaRequest"];
			};
		};
		responses: {
			/** @description A successful response. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["v1CreateSchemaResponse"];
				};
			};
			/** @description An unexpected error response. */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["rpcStatus"];
				};
			};
		};
	};
	SchemaService_ImportSchema: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["v1ImportSchemaRequest"];
			};
		};
		responses: {
			/** @description A successful response. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["v1ImportSchemaResponse"];
				};
			};
			/** @description An unexpected error response. */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["rpcStatus"];
				};
			};
		};
	};
	SchemaService_GetSchema: {
		parameters: {
			query?: {
				/** @description Schema version to retrieve. If omitted, returns the latest version. */
				version?: number;
			};
			header?: never;
			path: {
				/** @description Schema ID (UUID). */
				id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description A successful response. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["v1GetSchemaResponse"];
				};
			};
			/** @description An unexpected error response. */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["rpcStatus"];
				};
			};
		};
	};
	SchemaService_DeleteSchema: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Schema ID (UUID). Cascades to all versions, fields, and associated tenants. */
				id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description A successful response. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["v1DeleteSchemaResponse"];
				};
			};
			/** @description An unexpected error response. */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["rpcStatus"];
				};
			};
		};
	};
	SchemaService_UpdateSchema: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Schema ID (UUID). */
				id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["SchemaServiceUpdateSchemaBody"];
			};
		};
		responses: {
			/** @description A successful response. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["v1UpdateSchemaResponse"];
				};
			};
			/** @description An unexpected error response. */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["rpcStatus"];
				};
			};
		};
	};
	SchemaService_ExportSchema: {
		parameters: {
			query?: {
				/** @description Schema version to export. If omitted, exports the latest version. */
				version?: number;
			};
			header?: never;
			path: {
				/** @description Schema ID (UUID). */
				id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description A successful response. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["v1ExportSchemaResponse"];
				};
			};
			/** @description An unexpected error response. */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["rpcStatus"];
				};
			};
		};
	};
	SchemaService_PublishSchema: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Schema ID (UUID). */
				id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["SchemaServicePublishSchemaBody"];
			};
		};
		responses: {
			/** @description A successful response. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["v1PublishSchemaResponse"];
				};
			};
			/** @description An unexpected error response. */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["rpcStatus"];
				};
			};
		};
	};
	SchemaService_ListTenants: {
		parameters: {
			query?: {
				/** @description Filter by schema ID (UUID). If omitted, returns tenants across all schemas. */
				schemaId?: string;
				/** @description Maximum number of results to return. Defaults to 50, max 100. */
				pageSize?: number;
				/** @description Pagination token from a previous ListTenantsResponse. */
				pageToken?: string;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description A successful response. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["v1ListTenantsResponse"];
				};
			};
			/** @description An unexpected error response. */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["rpcStatus"];
				};
			};
		};
	};
	SchemaService_CreateTenant: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["v1CreateTenantRequest"];
			};
		};
		responses: {
			/** @description A successful response. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["v1CreateTenantResponse"];
				};
			};
			/** @description An unexpected error response. */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["rpcStatus"];
				};
			};
		};
	};
	SchemaService_GetTenant: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Tenant ID (UUID). */
				id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description A successful response. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["v1GetTenantResponse"];
				};
			};
			/** @description An unexpected error response. */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["rpcStatus"];
				};
			};
		};
	};
	SchemaService_DeleteTenant: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Tenant ID (UUID). Cascades to all config versions, values, and field locks. */
				id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description A successful response. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["v1DeleteTenantResponse"];
				};
			};
			/** @description An unexpected error response. */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["rpcStatus"];
				};
			};
		};
	};
	SchemaService_UpdateTenant: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Tenant ID (UUID). */
				id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["SchemaServiceUpdateTenantBody"];
			};
		};
		responses: {
			/** @description A successful response. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["v1UpdateTenantResponse"];
				};
			};
			/** @description An unexpected error response. */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["rpcStatus"];
				};
			};
		};
	};
	ConfigService_GetConfig: {
		parameters: {
			query?: {
				/** @description Config version to retrieve. If omitted, returns the latest version. */
				version?: number;
				/**
				 * @description When true, includes value-level descriptions in the response.
				 *     This bypasses the Redis cache and reads directly from the database.
				 */
				includeDescriptions?: boolean;
			};
			header?: never;
			path: {
				/** @description Tenant ID (UUID). */
				tenantId: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description A successful response. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["v1GetConfigResponse"];
				};
			};
			/** @description An unexpected error response. */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["rpcStatus"];
				};
			};
		};
	};
	ConfigService_ExportConfig: {
		parameters: {
			query?: {
				/** @description Config version to export. If omitted, exports the latest version. */
				version?: number;
			};
			header?: never;
			path: {
				/** @description Tenant ID (UUID). */
				tenantId: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description A successful response. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["v1ExportConfigResponse"];
				};
			};
			/** @description An unexpected error response. */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["rpcStatus"];
				};
			};
		};
	};
	ConfigService_GetField: {
		parameters: {
			query?: {
				/** @description Config version to read from. If omitted, reads from the latest version. */
				version?: number;
				/**
				 * @description When true, includes the value-level description.
				 *     This bypasses the Redis cache and reads directly from the database.
				 */
				includeDescription?: boolean;
			};
			header?: never;
			path: {
				/** @description Tenant ID (UUID). */
				tenantId: string;
				/** @description Dot-separated field path (e.g. "payments.fee"). */
				fieldPath: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description A successful response. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["v1GetFieldResponse"];
				};
			};
			/** @description An unexpected error response. */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["rpcStatus"];
				};
			};
		};
	};
	ConfigService_SetField: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Tenant ID (UUID). */
				tenantId: string;
				/** @description Dot-separated field path (e.g. "payments.fee"). */
				fieldPath: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["ConfigServiceSetFieldBody"];
			};
		};
		responses: {
			/** @description A successful response. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["v1SetFieldResponse"];
				};
			};
			/** @description An unexpected error response. */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["rpcStatus"];
				};
			};
		};
	};
	ConfigService_ImportConfig: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Tenant ID (UUID). */
				tenantId: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["ConfigServiceImportConfigBody"];
			};
		};
		responses: {
			/** @description A successful response. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["v1ImportConfigResponse"];
				};
			};
			/** @description An unexpected error response. */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["rpcStatus"];
				};
			};
		};
	};
	ConfigService_GetFields: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Tenant ID (UUID). */
				tenantId: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["ConfigServiceGetFieldsBody"];
			};
		};
		responses: {
			/** @description A successful response. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["v1GetFieldsResponse"];
				};
			};
			/** @description An unexpected error response. */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["rpcStatus"];
				};
			};
		};
	};
	ConfigService_SetFields: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Tenant ID (UUID). */
				tenantId: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["ConfigServiceSetFieldsBody"];
			};
		};
		responses: {
			/** @description A successful response. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["v1SetFieldsResponse"];
				};
			};
			/** @description An unexpected error response. */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["rpcStatus"];
				};
			};
		};
	};
	ConfigService_Subscribe: {
		parameters: {
			query?: {
				/**
				 * @description Field paths to filter on. If empty, receives changes for all fields.
				 *     Changes to fields not in this list are silently dropped.
				 */
				fieldPaths?: string[];
			};
			header?: never;
			path: {
				/** @description Tenant ID (UUID) to subscribe to. */
				tenantId: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description A successful response.(streaming responses) */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": {
						result?: components["schemas"]["v1SubscribeResponse"];
						error?: components["schemas"]["rpcStatus"];
					};
				};
			};
			/** @description An unexpected error response. */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["rpcStatus"];
				};
			};
		};
	};
	SchemaService_ListFieldLocks: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Tenant ID (UUID). */
				tenantId: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description A successful response. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["v1ListFieldLocksResponse"];
				};
			};
			/** @description An unexpected error response. */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["rpcStatus"];
				};
			};
		};
	};
	SchemaService_LockField: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Tenant ID (UUID). */
				tenantId: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["SchemaServiceLockFieldBody"];
			};
		};
		responses: {
			/** @description A successful response. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["v1LockFieldResponse"];
				};
			};
			/** @description An unexpected error response. */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["rpcStatus"];
				};
			};
		};
	};
	SchemaService_UnlockField: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Tenant ID (UUID). */
				tenantId: string;
				/** @description Dot-separated field path to unlock. */
				fieldPath: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description A successful response. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["v1UnlockFieldResponse"];
				};
			};
			/** @description An unexpected error response. */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["rpcStatus"];
				};
			};
		};
	};
	AuditService_GetUnusedFields: {
		parameters: {
			query?: {
				/**
				 * @description Fields not read since this time are considered unused.
				 *     Required — there is no "all time" default to avoid expensive full scans.
				 */
				since?: string;
			};
			header?: never;
			path: {
				/** @description Tenant ID (UUID). */
				tenantId: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description A successful response. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["v1GetUnusedFieldsResponse"];
				};
			};
			/** @description An unexpected error response. */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["rpcStatus"];
				};
			};
		};
	};
	AuditService_GetTenantUsage: {
		parameters: {
			query?: {
				/** @description Start of the time range. If omitted, includes all historical data. */
				startTime?: string;
				/** @description End of the time range. If omitted, includes up to the current time. */
				endTime?: string;
			};
			header?: never;
			path: {
				/** @description Tenant ID (UUID). */
				tenantId: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description A successful response. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["v1GetTenantUsageResponse"];
				};
			};
			/** @description An unexpected error response. */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["rpcStatus"];
				};
			};
		};
	};
	AuditService_GetFieldUsage: {
		parameters: {
			query?: {
				/** @description Start of the time range. If omitted, includes all historical data. */
				startTime?: string;
				/** @description End of the time range. If omitted, includes up to the current time. */
				endTime?: string;
			};
			header?: never;
			path: {
				/** @description Tenant ID (UUID). */
				tenantId: string;
				/** @description Dot-separated field path to query. */
				fieldPath: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description A successful response. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["v1GetFieldUsageResponse"];
				};
			};
			/** @description An unexpected error response. */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["rpcStatus"];
				};
			};
		};
	};
	ConfigService_ListVersions: {
		parameters: {
			query?: {
				/** @description Maximum number of results to return. Defaults to 50, max 100. */
				pageSize?: number;
				/** @description Pagination token from a previous ListVersionsResponse. */
				pageToken?: string;
			};
			header?: never;
			path: {
				/** @description Tenant ID (UUID). */
				tenantId: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description A successful response. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["v1ListVersionsResponse"];
				};
			};
			/** @description An unexpected error response. */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["rpcStatus"];
				};
			};
		};
	};
	ConfigService_GetVersion: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Tenant ID (UUID). */
				tenantId: string;
				/** @description The version number to retrieve. */
				version: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description A successful response. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["v1GetVersionResponse"];
				};
			};
			/** @description An unexpected error response. */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["rpcStatus"];
				};
			};
		};
	};
	ConfigService_RollbackToVersion: {
		parameters: {
			query?: {
				/**
				 * @description Description for the new rollback version. Defaults to
				 *     "Rollback to version N" if omitted.
				 */
				description?: string;
			};
			header?: never;
			path: {
				/** @description Tenant ID (UUID). */
				tenantId: string;
				/**
				 * @description The target version to rollback to. The full config at this version
				 *     is copied into a new version (the current version number + 1).
				 *     The target version itself is not modified.
				 */
				version: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description A successful response. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["v1RollbackToVersionResponse"];
				};
			};
			/** @description An unexpected error response. */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["rpcStatus"];
				};
			};
		};
	};
	VersionService_GetServerVersion: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description A successful response. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["v1GetServerVersionResponse"];
				};
			};
			/** @description An unexpected error response. */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["rpcStatus"];
				};
			};
		};
	};
}
